package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "PlaystationStore",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://store.playstation.com/",
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"geo": map[string]any{},
				"image": map[string]any{},
				"store": map[string]any{},
			},
		},
		"entity": map[string]any{
			"geo": map[string]any{
				"fields": []any{},
				"name": "geo",
				"op": map[string]any{
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"method": "GET",
								"orig": "/kamaji/api/chihiro/00_09_000/geo",
								"parts": []any{
									"kamaji",
									"api",
									"chihiro",
									"00_09_000",
									"geo",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"image": map[string]any{
				"fields": []any{},
				"name": "image",
				"op": map[string]any{
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"active": true,
											"example": 999,
											"kind": "param",
											"name": "age",
											"orig": "age",
											"reqd": true,
											"type": "`$INTEGER`",
											"index$": 0,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "container_id",
											"orig": "country",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 1,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "cusa",
											"orig": "cusa",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 2,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "language",
											"orig": "language",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 3,
										},
									},
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "bg_color",
											"orig": "bg_color",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "h",
											"orig": "h",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"example": 100,
											"kind": "query",
											"name": "opacity",
											"orig": "opacity",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "platform",
											"orig": "platform",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "w",
											"orig": "w",
											"reqd": false,
											"type": "`$INTEGER`",
										},
									},
								},
								"method": "GET",
								"orig": "/store/api/chihiro/00_09_000/container/{country}/{language}/{age}/{cusa}/image",
								"parts": []any{
									"store",
									"api",
									"chihiro",
									"00_09_000",
									"container",
									"{container_id}",
									"{language}",
									"{age}",
									"{cusa}",
									"image",
								},
								"rename": map[string]any{
									"param": map[string]any{
										"country": "container_id",
									},
								},
								"select": map[string]any{
									"exist": []any{
										"age",
										"bg_color",
										"container_id",
										"cusa",
										"h",
										"language",
										"opacity",
										"platform",
										"w",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{
						[]any{
							"container",
						},
					},
				},
			},
			"store": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "bucket",
						"req": true,
						"type": "`$STRING`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "bundle_child_type_id",
						"req": false,
						"type": "`$NUMBER`",
						"index$": 1,
					},
					map[string]any{
						"active": true,
						"name": "cloud_only_platform",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 2,
					},
					map[string]any{
						"active": true,
						"name": "container_type",
						"req": true,
						"type": "`$STRING`",
						"index$": 3,
					},
					map[string]any{
						"active": true,
						"name": "content_type",
						"req": true,
						"type": "`$STRING`",
						"index$": 4,
					},
					map[string]any{
						"active": true,
						"name": "default_sku",
						"req": true,
						"type": "`$OBJECT`",
						"index$": 5,
					},
					map[string]any{
						"active": true,
						"name": "game_content_type",
						"req": false,
						"type": "`$STRING`",
						"index$": 6,
					},
					map[string]any{
						"active": true,
						"name": "game_content_types_list",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 7,
					},
					map[string]any{
						"active": true,
						"name": "id",
						"req": true,
						"type": "`$STRING`",
						"index$": 8,
					},
					map[string]any{
						"active": true,
						"name": "image",
						"req": true,
						"type": "`$ARRAY`",
						"index$": 9,
					},
					map[string]any{
						"active": true,
						"name": "name",
						"req": true,
						"type": "`$STRING`",
						"index$": 10,
					},
					map[string]any{
						"active": true,
						"name": "parent_name",
						"req": false,
						"type": "`$STRING`",
						"index$": 11,
					},
					map[string]any{
						"active": true,
						"name": "playable_platform",
						"req": true,
						"type": "`$ARRAY`",
						"index$": 12,
					},
					map[string]any{
						"active": true,
						"name": "provider_name",
						"req": false,
						"type": "`$STRING`",
						"index$": 13,
					},
					map[string]any{
						"active": true,
						"name": "release_date",
						"req": true,
						"type": "`$STRING`",
						"index$": 14,
					},
					map[string]any{
						"active": true,
						"name": "restricted",
						"req": true,
						"type": "`$BOOLEAN`",
						"index$": 15,
					},
					map[string]any{
						"active": true,
						"name": "revision",
						"req": true,
						"type": "`$NUMBER`",
						"index$": 16,
					},
					map[string]any{
						"active": true,
						"name": "short_name",
						"req": true,
						"type": "`$STRING`",
						"index$": 17,
					},
					map[string]any{
						"active": true,
						"name": "timestamp",
						"req": true,
						"type": "`$NUMBER`",
						"index$": 18,
					},
					map[string]any{
						"active": true,
						"name": "top_category",
						"req": true,
						"type": "`$STRING`",
						"index$": 19,
					},
					map[string]any{
						"active": true,
						"name": "url",
						"req": true,
						"type": "`$STRING`",
						"index$": 20,
					},
				},
				"name": "store",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"active": true,
											"example": 999,
											"kind": "param",
											"name": "age",
											"orig": "age",
											"reqd": true,
											"type": "`$INTEGER`",
											"index$": 0,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "country",
											"orig": "country",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 1,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "language",
											"orig": "language",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 2,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "search_string",
											"orig": "search_string",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 3,
										},
									},
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "direction",
											"orig": "direction",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "game_content_type",
											"orig": "game_content_type",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "game_demo",
											"orig": "game_demo",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "game_type",
											"orig": "game_type",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "genre",
											"orig": "genre",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "platform",
											"orig": "platform",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "price",
											"orig": "price",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "relationship",
											"orig": "relationship",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "release_date",
											"orig": "release_date",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 1,
											"kind": "query",
											"name": "size",
											"orig": "size",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "sort",
											"orig": "sort",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 0,
											"kind": "query",
											"name": "start",
											"orig": "start",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "subtitle_lang",
											"orig": "subtitle_lang",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "top_category",
											"orig": "top_category",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "voice_lang",
											"orig": "voice_lang",
											"reqd": false,
											"type": "`$STRING`",
										},
									},
								},
								"method": "GET",
								"orig": "/store/api/chihiro/00_09_000/tumbler/{country}/{language}/{age}/{searchString}",
								"parts": []any{
									"store",
									"api",
									"chihiro",
									"00_09_000",
									"tumbler",
									"{country}",
									"{language}",
									"{age}",
									"{search_string}",
								},
								"rename": map[string]any{
									"param": map[string]any{
										"searchString": "search_string",
									},
								},
								"select": map[string]any{
									"exist": []any{
										"age",
										"country",
										"direction",
										"game_content_type",
										"game_demo",
										"game_type",
										"genre",
										"language",
										"platform",
										"price",
										"relationship",
										"release_date",
										"search_string",
										"size",
										"sort",
										"start",
										"subtitle_lang",
										"top_category",
										"voice_lang",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "list",
					},
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"active": true,
											"example": 999,
											"kind": "param",
											"name": "age",
											"orig": "age",
											"reqd": true,
											"type": "`$INTEGER`",
											"index$": 0,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "country",
											"orig": "country",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 1,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "cusa",
											"orig": "cusa",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 2,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "language",
											"orig": "language",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 3,
										},
									},
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "direction",
											"orig": "direction",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "game_content_type",
											"orig": "game_content_type",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "game_demo",
											"orig": "game_demo",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "game_type",
											"orig": "game_type",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "genre",
											"orig": "genre",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "platform",
											"orig": "platform",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "price",
											"orig": "price",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "relationship",
											"orig": "relationship",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "release_date",
											"orig": "release_date",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 1,
											"kind": "query",
											"name": "size",
											"orig": "size",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "sort",
											"orig": "sort",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 0,
											"kind": "query",
											"name": "start",
											"orig": "start",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "subtitle_lang",
											"orig": "subtitle_lang",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "top_category",
											"orig": "top_category",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "voice_lang",
											"orig": "voice_lang",
											"reqd": false,
											"type": "`$STRING`",
										},
									},
								},
								"method": "GET",
								"orig": "/store/api/chihiro/00_09_000/container/{country}/{language}/{age}/{cusa}",
								"parts": []any{
									"store",
									"api",
									"chihiro",
									"00_09_000",
									"container",
									"{country}",
									"{language}",
									"{age}",
									"{cusa}",
								},
								"select": map[string]any{
									"exist": []any{
										"age",
										"country",
										"cusa",
										"direction",
										"game_content_type",
										"game_demo",
										"game_type",
										"genre",
										"language",
										"platform",
										"price",
										"relationship",
										"release_date",
										"size",
										"sort",
										"start",
										"subtitle_lang",
										"top_category",
										"voice_lang",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"active": true,
											"example": 999,
											"kind": "param",
											"name": "age",
											"orig": "age",
											"reqd": true,
											"type": "`$INTEGER`",
											"index$": 0,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "country",
											"orig": "country",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 1,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "cusa",
											"orig": "cusa",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 2,
										},
										map[string]any{
											"active": true,
											"kind": "param",
											"name": "language",
											"orig": "language",
											"reqd": true,
											"type": "`$STRING`",
											"index$": 3,
										},
									},
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "direction",
											"orig": "direction",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 1,
											"kind": "query",
											"name": "size",
											"orig": "size",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "sort",
											"orig": "sort",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 0,
											"kind": "query",
											"name": "start",
											"orig": "start",
											"reqd": false,
											"type": "`$INTEGER`",
										},
									},
								},
								"method": "GET",
								"orig": "/chihiro-api/viewfinder/{country}/{language}/{age}/{cusa}",
								"parts": []any{
									"chihiro-api",
									"viewfinder",
									"{country}",
									"{language}",
									"{age}",
									"{cusa}",
								},
								"select": map[string]any{
									"exist": []any{
										"age",
										"country",
										"cusa",
										"direction",
										"language",
										"size",
										"sort",
										"start",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 1,
							},
						},
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{
						[]any{
							"viewfinder",
						},
						[]any{
							"container",
						},
						[]any{
							"tumbler",
						},
					},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
