# PlaystationStore SDK configuration


def make_config():
    return {
        "main": {
            "name": "PlaystationStore",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://store.playstation.com/",
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "geo": {},
                "image": {},
                "store": {},
            },
        },
        "entity": {
      "geo": {
        "fields": [],
        "name": "geo",
        "op": {
          "load": {
            "name": "load",
            "points": [
              {
                "method": "GET",
                "orig": "/kamaji/api/chihiro/00_09_000/geo",
                "parts": [
                  "kamaji",
                  "api",
                  "chihiro",
                  "00_09_000",
                  "geo",
                ],
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "args": {},
                "select": {},
                "index$": 0,
              },
            ],
            "input": "data",
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "image": {
        "fields": [],
        "name": "image",
        "op": {
          "load": {
            "name": "load",
            "points": [
              {
                "args": {
                  "params": [
                    {
                      "example": 999,
                      "kind": "param",
                      "name": "age",
                      "orig": "age",
                      "reqd": True,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "container_id",
                      "orig": "country",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "cusa",
                      "orig": "cusa",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "language",
                      "orig": "language",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                  "query": [
                    {
                      "kind": "query",
                      "name": "bg_color",
                      "orig": "bg_color",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "h",
                      "orig": "h",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "example": 100,
                      "kind": "query",
                      "name": "opacity",
                      "orig": "opacity",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "platform",
                      "orig": "platform",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "w",
                      "orig": "w",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/store/api/chihiro/00_09_000/container/{country}/{language}/{age}/{cusa}/image",
                "parts": [
                  "store",
                  "api",
                  "chihiro",
                  "00_09_000",
                  "container",
                  "{container_id}",
                  "{language}",
                  "{age}",
                  "{cusa}",
                  "image",
                ],
                "rename": {
                  "param": {
                    "country": "container_id",
                  },
                },
                "select": {
                  "exist": [
                    "age",
                    "bg_color",
                    "container_id",
                    "cusa",
                    "h",
                    "language",
                    "opacity",
                    "platform",
                    "w",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 0,
              },
            ],
            "input": "data",
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [
            [
              "container",
            ],
          ],
        },
      },
      "store": {
        "fields": [
          {
            "name": "bucket",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 0,
          },
          {
            "name": "bundle_child_type_id",
            "req": False,
            "type": "`$NUMBER`",
            "active": True,
            "index$": 1,
          },
          {
            "name": "cloud_only_platform",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 2,
          },
          {
            "name": "container_type",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 3,
          },
          {
            "name": "content_type",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 4,
          },
          {
            "name": "default_sku",
            "req": True,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 5,
          },
          {
            "name": "game_content_type",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 6,
          },
          {
            "name": "game_content_types_list",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 7,
          },
          {
            "name": "id",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 8,
          },
          {
            "name": "image",
            "req": True,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 9,
          },
          {
            "name": "name",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 10,
          },
          {
            "name": "parent_name",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 11,
          },
          {
            "name": "playable_platform",
            "req": True,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 12,
          },
          {
            "name": "provider_name",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 13,
          },
          {
            "name": "release_date",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 14,
          },
          {
            "name": "restricted",
            "req": True,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 15,
          },
          {
            "name": "revision",
            "req": True,
            "type": "`$NUMBER`",
            "active": True,
            "index$": 16,
          },
          {
            "name": "short_name",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 17,
          },
          {
            "name": "timestamp",
            "req": True,
            "type": "`$NUMBER`",
            "active": True,
            "index$": 18,
          },
          {
            "name": "top_category",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 19,
          },
          {
            "name": "url",
            "req": True,
            "type": "`$STRING`",
            "active": True,
            "index$": 20,
          },
        ],
        "name": "store",
        "op": {
          "list": {
            "name": "list",
            "points": [
              {
                "args": {
                  "params": [
                    {
                      "example": 999,
                      "kind": "param",
                      "name": "age",
                      "orig": "age",
                      "reqd": True,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "country",
                      "orig": "country",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "language",
                      "orig": "language",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "search_string",
                      "orig": "search_string",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                  "query": [
                    {
                      "kind": "query",
                      "name": "direction",
                      "orig": "direction",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "game_content_type",
                      "orig": "game_content_type",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "game_demo",
                      "orig": "game_demo",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "game_type",
                      "orig": "game_type",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "genre",
                      "orig": "genre",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "platform",
                      "orig": "platform",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "price",
                      "orig": "price",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "relationship",
                      "orig": "relationship",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "release_date",
                      "orig": "release_date",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "example": 1,
                      "kind": "query",
                      "name": "size",
                      "orig": "size",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "sort",
                      "orig": "sort",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "example": 0,
                      "kind": "query",
                      "name": "start",
                      "orig": "start",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "subtitle_lang",
                      "orig": "subtitle_lang",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "top_category",
                      "orig": "top_category",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "voice_lang",
                      "orig": "voice_lang",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/store/api/chihiro/00_09_000/tumbler/{country}/{language}/{age}/{searchString}",
                "parts": [
                  "store",
                  "api",
                  "chihiro",
                  "00_09_000",
                  "tumbler",
                  "{country}",
                  "{language}",
                  "{age}",
                  "{search_string}",
                ],
                "rename": {
                  "param": {
                    "searchString": "search_string",
                  },
                },
                "select": {
                  "exist": [
                    "age",
                    "country",
                    "direction",
                    "game_content_type",
                    "game_demo",
                    "game_type",
                    "genre",
                    "language",
                    "platform",
                    "price",
                    "relationship",
                    "release_date",
                    "search_string",
                    "size",
                    "sort",
                    "start",
                    "subtitle_lang",
                    "top_category",
                    "voice_lang",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 0,
              },
            ],
            "input": "data",
            "key$": "list",
          },
          "load": {
            "name": "load",
            "points": [
              {
                "args": {
                  "params": [
                    {
                      "example": 999,
                      "kind": "param",
                      "name": "age",
                      "orig": "age",
                      "reqd": True,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "country",
                      "orig": "country",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "cusa",
                      "orig": "cusa",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "language",
                      "orig": "language",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                  "query": [
                    {
                      "kind": "query",
                      "name": "direction",
                      "orig": "direction",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "game_content_type",
                      "orig": "game_content_type",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "game_demo",
                      "orig": "game_demo",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "game_type",
                      "orig": "game_type",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "genre",
                      "orig": "genre",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "platform",
                      "orig": "platform",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "price",
                      "orig": "price",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "relationship",
                      "orig": "relationship",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "release_date",
                      "orig": "release_date",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "example": 1,
                      "kind": "query",
                      "name": "size",
                      "orig": "size",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "sort",
                      "orig": "sort",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "example": 0,
                      "kind": "query",
                      "name": "start",
                      "orig": "start",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "subtitle_lang",
                      "orig": "subtitle_lang",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "top_category",
                      "orig": "top_category",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "voice_lang",
                      "orig": "voice_lang",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/store/api/chihiro/00_09_000/container/{country}/{language}/{age}/{cusa}",
                "parts": [
                  "store",
                  "api",
                  "chihiro",
                  "00_09_000",
                  "container",
                  "{country}",
                  "{language}",
                  "{age}",
                  "{cusa}",
                ],
                "select": {
                  "exist": [
                    "age",
                    "country",
                    "cusa",
                    "direction",
                    "game_content_type",
                    "game_demo",
                    "game_type",
                    "genre",
                    "language",
                    "platform",
                    "price",
                    "relationship",
                    "release_date",
                    "size",
                    "sort",
                    "start",
                    "subtitle_lang",
                    "top_category",
                    "voice_lang",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 0,
              },
              {
                "args": {
                  "params": [
                    {
                      "example": 999,
                      "kind": "param",
                      "name": "age",
                      "orig": "age",
                      "reqd": True,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "country",
                      "orig": "country",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "cusa",
                      "orig": "cusa",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "kind": "param",
                      "name": "language",
                      "orig": "language",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                  "query": [
                    {
                      "kind": "query",
                      "name": "direction",
                      "orig": "direction",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "example": 1,
                      "kind": "query",
                      "name": "size",
                      "orig": "size",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                    {
                      "kind": "query",
                      "name": "sort",
                      "orig": "sort",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "example": 0,
                      "kind": "query",
                      "name": "start",
                      "orig": "start",
                      "reqd": False,
                      "type": "`$INTEGER`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/chihiro-api/viewfinder/{country}/{language}/{age}/{cusa}",
                "parts": [
                  "chihiro-api",
                  "viewfinder",
                  "{country}",
                  "{language}",
                  "{age}",
                  "{cusa}",
                ],
                "select": {
                  "exist": [
                    "age",
                    "country",
                    "cusa",
                    "direction",
                    "language",
                    "size",
                    "sort",
                    "start",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 1,
              },
            ],
            "input": "data",
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [
            [
              "viewfinder",
            ],
            [
              "container",
            ],
            [
              "tumbler",
            ],
          ],
        },
      },
    },
    }
